name: tests-ideas
on:
  pull_request:
    paths:
      - 'ideas/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd ideas && npm install && npm run test:ci
